distances:
    # Chat before this distance will always be non-obfuscated (in blocks)
    clearBefore: 30

    # Chat after this distance will always be fully obfuscated (in blocks)
    obfuscatedAfter: 150

# Remove colors from all partially or completly obfuscated messages?
# The color is only removed from obfuscated parts.
clearObfuscatedMessagesColors: false

replacements:
    # Hide the obfuscated part using Minecraft's MAGIC formatter.
    magic: true

    # Hide the obfuscated part by replacing the characters with a random value.
    # Use this to prevent players to consult their game log to see through the obfuscation.
    # You'll lose the characters' width.
    replaceObfuscatedText: false

yell:
    # The prefixes of the yell messages.
    # The full-text prefix is prepended to the whole message, before "<nickname>".
    # The message prefix is prepended to the player's message, after the "<nickname> ".
    # You can use formatting codes here, either using 'ยง' or '&'.
    prefix:
        full-text: "\u2756 "
        message: ""
